//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblCustomer
    {
        public long CustID { get; set; }

        [Required(ErrorMessage = " *")]
        [StringLength(50, ErrorMessage = "Less than 50 characters")]
        public string CustName { get; set; }

        [Required(ErrorMessage = " *")]
        [StringLength(50, ErrorMessage = "Less than 50 characters")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string CustEmail { get; set; }

        [StringLength(256, ErrorMessage = "Less than 256 characters")]
        public string CustAddress { get; set; }

        [StringLength(50, ErrorMessage = "Less than 50 characters")]
        public string CustContact { get; set; }
    }
}
